// Note: this list is very out-of-date now
export const cypherFunctions = `
abs
acos
apoc.agg.first
apoc.agg.graph
apoc.agg.last
apoc.agg.maxItems
apoc.agg.median
apoc.agg.minItems
apoc.agg.nth
apoc.agg.percentiles
apoc.agg.product
apoc.agg.slice
apoc.agg.statistics
apoc.any.properties
apoc.any.property
apoc.bitwise.op
apoc.coll.avg
apoc.coll.combinations
apoc.coll.contains
apoc.coll.containsAll
apoc.coll.containsAllSorted
apoc.coll.containsDuplicates
apoc.coll.containsSorted
apoc.coll.different
apoc.coll.disjunction
apoc.coll.dropDuplicateNeighbors
apoc.coll.duplicates
apoc.coll.duplicatesWithCount
apoc.coll.fill
apoc.coll.flatten
apoc.coll.frequencies
apoc.coll.frequenciesAsMap
apoc.coll.indexOf
apoc.coll.insert
apoc.coll.insertAll
apoc.coll.intersection
apoc.coll.isEqualCollection
apoc.coll.max
apoc.coll.min
apoc.coll.occurrences
apoc.coll.pairs
apoc.coll.pairsMin
apoc.coll.partition
apoc.coll.randomItem
apoc.coll.randomItems
apoc.coll.remove
apoc.coll.removeAll
apoc.coll.reverse
apoc.coll.set
apoc.coll.shuffle
apoc.coll.sort
apoc.coll.sortMaps
apoc.coll.sortMulti
apoc.coll.sortNodes
apoc.coll.sortText
apoc.coll.subtract
apoc.coll.sum
apoc.coll.sumLongs
apoc.coll.toSet
apoc.coll.union
apoc.coll.unionAll
apoc.coll.zip
apoc.convert.fromJsonList
apoc.convert.fromJsonMap
apoc.convert.getJsonProperty
apoc.convert.getJsonPropertyMap
apoc.convert.toBoolean
apoc.convert.toBooleanList
apoc.convert.toFloat
apoc.convert.toIntList
apoc.convert.toInteger
apoc.convert.toJson
apoc.convert.toList
apoc.convert.toMap
apoc.convert.toNode
apoc.convert.toNodeList
apoc.convert.toRelationship
apoc.convert.toRelationshipList
apoc.convert.toSet
apoc.convert.toSortedJsonMap
apoc.convert.toString
apoc.convert.toStringList
apoc.create.uuid
apoc.create.vNode
apoc.create.vRelationship
apoc.create.virtual.fromNode
apoc.cypher.runFirstColumn
apoc.cypher.runFirstColumnMany
apoc.cypher.runFirstColumnSingle
apoc.data.domain
apoc.data.url
apoc.date.add
apoc.date.convert
apoc.date.convertFormat
apoc.date.currentTimestamp
apoc.date.field
apoc.date.fields
apoc.date.format
apoc.date.fromISO8601
apoc.date.parse
apoc.date.parseAsZonedDateTime
apoc.date.systemTimezone
apoc.date.toISO8601
apoc.date.toYears
apoc.diff.nodes
apoc.hashing.fingerprint
apoc.hashing.fingerprintGraph
apoc.hashing.fingerprinting
apoc.json.path
apoc.label.exists
apoc.map.clean
apoc.map.flatten
apoc.map.fromLists
apoc.map.fromNodes
apoc.map.fromPairs
apoc.map.fromValues
apoc.map.get
apoc.map.groupBy
apoc.map.groupByMulti
apoc.map.merge
apoc.map.mergeList
apoc.map.mget
apoc.map.removeKey
apoc.map.removeKeys
apoc.map.setEntry
apoc.map.setKey
apoc.map.setLists
apoc.map.setPairs
apoc.map.setValues
apoc.map.sortedProperties
apoc.map.submap
apoc.map.updateTree
apoc.map.values
apoc.math.maxByte
apoc.math.maxDouble
apoc.math.maxInt
apoc.math.maxLong
apoc.math.minByte
apoc.math.minDouble
apoc.math.minInt
apoc.math.minLong
apoc.math.round
apoc.meta.cypher.isType
apoc.meta.cypher.type
apoc.meta.cypher.types
apoc.meta.isType
apoc.meta.type
apoc.meta.typeName
apoc.meta.types
apoc.node.degree
apoc.node.degree.in
apoc.node.degree.out
apoc.node.id
apoc.node.labels
apoc.node.relationship.exists
apoc.node.relationship.types
apoc.node.relationships.exist
apoc.nodes.connected
apoc.nodes.isDense
apoc.nodes.relationship.types
apoc.nodes.relationships.exist
apoc.number.arabicToRoman
apoc.number.exact.add
apoc.number.exact.div
apoc.number.exact.mul
apoc.number.exact.sub
apoc.number.exact.toExact
apoc.number.exact.toFloat
apoc.number.exact.toInteger
apoc.number.format
apoc.number.parseFloat
apoc.number.parseInt
apoc.number.romanToArabic
apoc.path.combine
apoc.path.create
apoc.path.elements
apoc.path.slice
apoc.rel.id
apoc.rel.type
apoc.schema.node.constraintExists
apoc.schema.node.indexExists
apoc.schema.relationship.constraintExists
apoc.scoring.existence
apoc.scoring.pareto
apoc.static.get
apoc.static.getAll
apoc.temporal.format
apoc.temporal.formatDuration
apoc.temporal.toZonedTemporal
apoc.text.base64Decode
apoc.text.base64Encode
apoc.text.base64UrlDecode
apoc.text.base64UrlEncode
apoc.text.byteCount
apoc.text.bytes
apoc.text.camelCase
apoc.text.capitalize
apoc.text.capitalizeAll
apoc.text.charAt
apoc.text.clean
apoc.text.code
apoc.text.compareCleaned
apoc.text.decapitalize
apoc.text.decapitalizeAll
apoc.text.distance
apoc.text.doubleMetaphone
apoc.text.format
apoc.text.fuzzyMatch
apoc.text.hammingDistance
apoc.text.hexCharAt
apoc.text.hexValue
apoc.text.indexOf
apoc.text.indexesOf
apoc.text.jaroWinklerDistance
apoc.text.join
apoc.text.levenshteinDistance
apoc.text.levenshteinSimilarity
apoc.text.lpad
apoc.text.phonetic
apoc.text.random
apoc.text.regexGroups
apoc.text.regreplace
apoc.text.repeat
apoc.text.replace
apoc.text.rpad
apoc.text.slug
apoc.text.snakeCase
apoc.text.sorensenDiceSimilarity
apoc.text.split
apoc.text.swapCase
apoc.text.toCypher
apoc.text.toUpperCase
apoc.text.upperCamelCase
apoc.text.urldecode
apoc.text.urlencode
apoc.trigger.nodesByLabel
apoc.trigger.propertiesByKey
apoc.util.md5
apoc.util.sha1
apoc.util.sha256
apoc.util.sha384
apoc.util.sha512
apoc.version
apoc.xml.parse
asin
atan
atan2
avg
ceil
coalesce
collect
cos
cot
count
date
date.realtime
date.statement
date.transaction
date.truncate
datetime
datetime.fromepoch
datetime.fromepochmillis
datetime.realtime
datetime.statement
datetime.transaction
datetime.truncate
degrees
distance
duration
duration.between
duration.inDays
duration.inMonths
duration.inSeconds
e
endNode
exists
exp
file
floor
haversin
head
id
keys
labels
last
left
length
linenumber
localdatetime
localdatetime.realtime
localdatetime.statement
localdatetime.transaction
localdatetime.truncate
localtime
localtime.realtime
localtime.statement
localtime.transaction
localtime.truncate
log
log10
ltrim
max
min
nodes
percentileCont
percentileDisc
pi
point
properties
radians
rand
randomUUID
range
reduce
relationships
replace
reverse
right
round
rtrim
sign
sin
size
split
sqrt
startNode
stdev
stdevp
substring
sum
tail
tan
time
time.realtime
time.statement
time.transaction
time.truncate
toBoolean
toFloat
toInteger
toLower
toString
toUpper
trim
type
`